global:
  workspace:
    path: C:\Users\ps\Documents\AutoResearch_Workspace
    papers_database: C:\Users\ps\Documents\AutoResearch_Workspace\papers.db
projects:
- name: Default
  path: C:\Users\ps\Documents\AutoResearch_Workspace\Default
  created_date: '2025-05-22'
  status: active
  description: Default project automatically created.
  structure:
    references:
      path: ./References
      database: ./References/references.db
    literature_review:
      path: ./Literature_Review
    proposal:
      path: ./Proposal
    experiment:
      path: ./Experiment
    manuscript:
      path: ./Manuscript
